# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for prepare-carbonio-vms
  - import_tasks: set-repos.yml
  - import_tasks: set-os.yml
  - import_tasks: update-os.yml
  - import_tasks: minimize-swap.yml
  - import_tasks: set-zextras-repos.yml
