---
  - name: Add TrustedIp
    become: true
    become_method: su
    become_user: zextras
    command: '/opt/zextras/bin/zmprov mcf +zimbraMailTrustedIP {{ansible_default_ipv4.address}}'
    when: inventory_hostname in groups["proxyServers"]
    tags:
      - fix-config   

  - name: Set smtp hostname for MTA servers
    become: true
    become_method: su
    become_user: zextras
    command: '/opt/zextras/bin/zmprov ms {{ ansible_fqdn }} zimbraSmtpHostname localhost zimbraSmtpPort 25'
    when: inventory_hostname in groups["mtaServers"]
    tags:
      - fix-config   

  - name: Fix memcached config
    become: true
    become_method: su
    become_user: zextras
    command: '/opt/zextras/bin/zmprov ms {{ ansible_fqdn }} zimbraMemcachedBindAddress {{ansible_default_ipv4.address}}'
    when: inventory_hostname in groups["proxyServers"] and (groups['filesServers'] | length > 0 or groups['docsServers'] | length > 0 or groups['previewServers'] | length > 0)
    tags:
      - fix-config  

  - name: Restart memcached
    become: true
    become_method: su
    become_user: zextras
    command: '/opt/zextras/bin/zmmemcachedctl restart'
    when: inventory_hostname in groups["proxyServers"] and (groups['filesServers'] | length > 0 or groups['docsServers'] | length > 0 or groups['previewServers'] | length > 0)
    tags:
      - fix-config
      
  - name: Reconfigure preview memcache
    replace:
      path: /etc/carbonio/preview/config.ini
      regexp: "127.0.0.1:11211"
      replace: "{{ hostvars[groups['proxyServers'][0]].inventory_hostname }}:11211"
    notify:  restart_preview
    when: inventory_hostname in groups["previewServers"]
    tags:
      - fix-config   
      
  - name: Reconfigure preview lookup handler
    replace:
      path: /etc/carbonio/preview/config.ini
      regexp: "127.0.0.1:7072"
      replace: "{{ hostvars[groups['applicationServers'][0]].inventory_hostname }}:7072"
    notify:  restart_preview
    when: inventory_hostname in groups["previewServers"]
    tags:
      - fix-config
      
  - name: Configure public service hostname
    become: true
    become_method: su
    become_user: zextras
    command: "/opt/zextras/bin/zmprov mcf zimbraPublicServiceHostname {{ hostvars[inventory_hostname].webmailHostname }}"
    when: inventory_hostname in groups["proxyServers"] and hostvars[inventory_hostname].webmailHostname is defined
    tags:
      - fix-config

  - name: Manage Videoserver password
    ansible.builtin.set_fact:
       carbonio_videoserver_password: "{{ lookup('ansible.builtin.password', inventory_file + '_videoserver_password',  chars=['ascii_letters', 'digits'], length=8) }}"
    when: inventory_hostname in groups["applicationServers"]
    tags:
      - fix-config   
    
  - name: Set videoservers to use
    become: true
    become_method: su
    become_user: zextras
    command: "carbonio chats video-server add {{item}} port 8188 servlet_port 8090 secret {{ carbonio_videoserver_password }}" 
    loop: "{{ groups['videoServers'] }}"    
    when: inventory_hostname in groups["applicationServers"][0]
    tags:
      - fix-config
      
  - name: Start and enable service videoserver
    ansible.builtin.systemd:
      name: videoserver
      state: started
      enabled: true
    when: inventory_hostname in groups["videoServers"]
    tags:
      - fix-config
      