---
# tasks file for execute-pending-setups
  - import_tasks: execute-carbonio-pending-setups.yml
  - import_tasks: execute-dbconnectors-bootstrap.yml
  - import_tasks: configure-videoserver.yml
  - import_tasks: execute-config-fixes.yml
  - import_tasks: execute-post-install-cmds.yml
