---
  - name: Install Carbonio Master Directoryserver Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ ds_packages }}"
    when: ansible_os_family == "Debian"  and (inventory_hostname in groups["masterDirectoryServers"] or inventory_hostname in groups["replicaDirectoryServers"])
    tags:
      - install-directory-server

  - name: Install Carbonio Master Directoryserver RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ ds_packages }}"
    when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and (inventory_hostname in groups["masterDirectoryServers"] or inventory_hostname in groups["replicaDirectoryServers"])
    tags:
      - install-directory-server