---
  - name: Install pgpool on Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
       - "{{ pgpool_packages_ubuntu }}"
    when: ansible_os_family == "Debian" and (inventory_hostname in groups["dbsConnectorServers"] and inventory_hostname not in groups["postgresServers"])
    tags:
       - install-pgpool

  - name: Install pgpool on RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
       - "{{ pgpool_packages_rhel }}"
    when: ansible_os_family == "RedHat" and (inventory_hostname in groups["dbsConnectorServers"] and inventory_hostname not in groups["postgresServers"])
    tags:
       - install-pgpool      