# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for pre-installation_checks
  - import_tasks: workstreamservers_check.yml
  - import_tasks: dbconnectors_checks.yml
  - import_tasks: consul_checks.yml
  - import_tasks: postgres_checks.yml
  - import_tasks: directory_server_checks.yml